# Scoped service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "operator.fullname" . }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Values.namespace }}
automountServiceAccountToken: true
---
# Access for the service account
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "operator.fullname" . }}
rules:
  - apiGroups: ["sinabro.io"]
    resources: ["sinabros", "sinabros/status"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["events.k8s.io"]
    resources: ["events"]
    verbs: ["create"]
---
# Binding the role to the account
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "operator.fullname" . }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Values.namespace }}
  name: {{ include "operator.fullname" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io