[package]
name = "sinabro"
version = "0.0.1"
authors = ["Wongyu Lee <kyu21@outlook.com>"]
description = "eBPF-based Networking, Security, and Observability"
license = "Apache-2.0"
edition = "2021"

[features]
default = []
telemetry = ["tonic", "opentelemetry-otlp"]

[dependencies]
axum = "0.6.18"
tokio = { version = "1.28.2", features = ["full"] }
kube = { version = "0.83.0", features = ["runtime", "derive"] }
k8s-openapi = { version = "0.18.0", features = ["v1_26"] }
futures = "0.3.28"
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.96"
serde_yaml = "0.9.21"
tracing = "0.1.37"
thiserror = "1.0.40"
anyhow = "1.0.71"
prometheus = "0.13.3"
schemars = { version = "0.8.12", features = ["chrono"] }
chrono = { version = "0.4.26", features = ["serde"] }
tracing-opentelemetry = "0.19.0"
tracing-subscriber = { version = "0.3.17", features = ["json", "env-filter"] }
opentelemetry = { version = "0.19.0", features = ["trace", "rt-tokio"] }
opentelemetry-otlp = { version = "0.12.0", features = ["tokio"], optional = true }
tonic = { version = "0.8", optional = true } # 0.9 blocked on opentelemetry-otlp release

